#!/usr/bin/env bash
#Redirect to a web page
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/error.html
route="/etc/nginx/sites-enabled/default"
place="\\\tlocation /redirect_me {\n\t\t return 301 https://github.com/andresjjn/;\n\t}\n"
sudo sed -i "30i $place" "$route"
error="\\\terror_page 404 /error.html;\n\tlocation = /error.html {\n\t\troot /var/www/html/;\n\t\tinternal;\n\t}"
sudo sed -i "34i $error" "$route"
sudo service nginx restart
