#!/usr/bin/env bash
#This script displays 5 times the ping between the pc and a ip pass like argument
if [ $# -eq 0 ];
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    eval ping "$1" -c 5
fi
