#!/usr/bin/env bash
#This script displays just username, user id and Home directory path for the user
#in /etc/passwd file
while IFS= read -r l
do
        echo "$l" | cut -d ':' --fields=1,3,6
done < "/etc/passwd"
