#!/usr/bin/env bash
#This script print 10 times "Holberton School" and in 4th line print "bad luck"
#and "good lock" in 8th line
i=0
while (( i<10 ))
do
        if [ $i -eq 3 ]
        then
                echo "bad luck" 
        elif [ $i -eq 7 ] 
        then
                echo "good luck"
        else
                echo "Holberton School" 
        fi
        i=$(( i+1 ))
done
