#!/usr/bin/env bash
#This script print a count from 1 to 20 with different messeges in some lines
i=0
while (( i<20 ))
do
        case $i in
                3)      echo  $(( i+1 ))
                        echo "bad luck from China"
                ;; 
                8)      echo  $(( i+1 ))
                        echo "bad luck from Japan"
                ;;
                16)     echo  $(( i+1 ))
                        echo "bad luck from Italy"
                ;;
                *)      echo  $(( i+1 ))
                ;;
        esac
        i=$(( i+1 ))
done
