#!/usr/bin/env bash
#This script print 10 times "Holberton School" and in 9th line print also "Hi"
i=0
while (( i<20 ))
do
        case $i in
                3)      echo  $(( i+1 ))
                        echo "bad luck from China"
                ;; 
                8)      echo  $(( i+1 ))
                        echo "bad luck from Japan"
                ;;
                16)     echo  $(( i+1 ))
                        echo "bad luck from Italy"
                ;;
                *)      echo  $(( i+1 ))
                ;;
        esac
        i=$(( i+1 ))
done
