#!/usr/bin/env bash
#This script show a clock starting from hour:0 to hour: 12 and 59 min
i=0
j=1
while (( i<=12 ))
do
        j=1
        echo "Hour: $i"
        while (( j<60 )) 
        do
                echo $j
                j=$(( j+1 ))
        done
        i=$(( i+1 ))
done
