#!/usr/bin/env bash
#This script print 10 times "Holberton School"
i=0
j=1
while (( i<=12 ))
do
        j=1
        echo "Hour: $i"
        while (( j<60 )) 
        do
                echo $j
                j=$(( j+1 ))
        done
        i=$(( i+1 ))
done
