#!/usr/bin/env bash
#This script modify what resolves locahost and facebook.com updating /etc/hosts
sudo sed -i".bak" "/localhost/d" /etc/hosts
sudo sed -i '1 i\127.0.0.2 localhost' /etc/hosts
sudo sed -i '1 i\8.8.8.8 facebook.com' /etc/hosts
