#!/usr/bin/env bash
#This script modify what resolves locahost and facebook.com updating /etc/hosts
cp /etc/hosts ~/host_tem
sed -i".bak" "/localhost/d" ~/host_tem
sed -i '1 i\127.0.0.2 localhost' ~/host_tem
sed -i '1 i\8.8.8.8 facebook.com' ~/host_tem
cp -f ~/host_tem /etc/hosts
